variable "key_name" {}
variable "public_key_path" {}
variable "vpc_2_cidr" {}
variable "vpc_1_cidr" {}
variable "vpc_3_cidr" {}
variable "vpc_1_private_cidr" {}
variable "vpc_2_private_cidr" {}
variable "vpc_3_public_cidr" {}
variable "AWS_DEFAULT_REGION" {}
variable "AWS_ACCESS_KEY_ID" {}
variable "AWS_SECRET_ACCESS_KEY" {}
