version: 2.1

executors:
  terraform:
    docker:
      - image: hashicorp/terraform:1.5.0
    working_directory: ~/repo
    environment:
      AWS_ACCESS_KEY_ID: << pipeline.parameters.aws_access_key_id >>
      AWS_SECRET_ACCESS_KEY: << pipeline.parameters.aws_secret_access_key >>
      AWS_DEFAULT_REGION: << pipeline.parameters.aws_default_region >>

parameters:
  aws_access_key_id:
    type: string
    default: ""  # Specify a placeholder or actual value if required
    description: "AWS Access Key ID"
  aws_secret_access_key:
    type: string
    default: ""  # Specify a placeholder or actual value if required
    description: "AWS Secret Access Key"
  aws_default_region:
    type: string
    default: "us-east-1"  # Specify a default region, e.g., "us-east-1"
    description: "AWS Region"

jobs:
  terraform-plan:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: terraform init
      - run:
          name: Terraform Plan
          command: |
            terraform plan -var="AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" -var="AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" -var="AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}"

  terraform-apply:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: terraform init
      - run:
          name: Terraform Apply
          command: |
            terraform apply -auto-approve -var="AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" -var="AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" -var="AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}"

  terraform-destroy:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: terraform init
      - run:
          name: Check for Destroy Keyword in Commit Message
          command: |
            if git log -1 --pretty=%B | grep -q '[destroy]'; then
              echo "Destroy keyword found, proceeding with destroy."
            else
              echo "Destroy keyword not found, skipping destroy."
              exit 0
      - run:
          name: Terraform Destroy
          command: |
            terraform destroy -auto-approve -var="AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" -var="AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" -var="AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}"

workflows:
  terraform-workflow:
    jobs:
      - terraform-plan
      - terraform-apply:
          requires:
            - terraform-plan
      - terraform-destroy:
          requires:
            - terraform-apply
          filters:
            branches:
              only: main
